#!/bin/sh --
# sx - start an xserver
# requires xauth Xorg /dev/urandom

cleanup() {
    if [ "$pid" ] && kill -0 "$pid" 2> /dev/null; then
        kill "$pid"
        wait "$pid"
        xorg=$?
    fi

    if ! stty "$stty"; then
        stty sane
    fi

    xauth remove :"$tty"

    if [ "$1" = exit ]; then
        exit "${xorg:-0}"
    fi
}

stty=$(stty -g)
tty=$(tty)
tty=${tty#/dev/tty}

cfgdir=${XDG_CONFIG_HOME:-$HOME/.config}/sx
datadir=${XDG_DATA_HOME:-$HOME/.local/share}/sx
mkdir -p -- "$cfgdir" "$datadir"

export XAUTHORITY="${XAUTHORITY:-$datadir/xauthority}"
touch -- "$XAUTHORITY"

xauth add :"$tty" MIT-MAGIC-COOKIE-1 "$(od -An -N16 -tx /dev/urandom | tr -d ' ')"

trap 'cleanup; trap - INT; kill -INT "$$"' INT
trap 'cleanup exit' EXIT HUP TERM QUIT

# Xorg will check whether it inherited a USR1 with a disposition of SIG_IGN and
# use this state to reply back to the parent process with its own USR1.
# This is done to indicate that the server is ready to accept connections.
# Taking advantage of this feature allows launching the client directly from a
# USR1 signal trap which obviates the need to poll for server readiness.
trap 'DISPLAY=:$tty exec "${@:-$cfgdir/sxrc}" & wait "$!"' USR1
(trap '' USR1 && exec Xorg :"$tty" -keeptty vt"$tty" -noreset -auth "$XAUTHORITY") & pid=$!
wait "$pid"

export DISPLAY=":1"

xrandr --output DP-2 --mode 1920x1080 --rate 144.00 --primary
xrandr --output HDMI-0 --mode 1920x1080 --rate 60.00 --rotate left --left-of DP-2 --rate 60.00
xrandr --output DP-1 --mode 1920x1080 --right-of DP-2 --rate 60.00

xrdb /home/sean/.config/Xresources &
xrdb -merge /home/sean/.config/Xdefaults &
unset XDG_RUNTIME_DIR
export XDG_RUNTIME_DIR=$(mktemp -d /tmp/$(id -u)-runtime-dir.XXX)
killall pulseaudio
killall dunst
# there should be no errors, so we can simply just yeet all output
# I will save the dwm log because if that crashes then something is very wrong 
pulseaudio --daemonize=no --exit-idle-time=-1 > /dev/null 2>&1 &
dunst > /dev/null 2>&1 &
/home/sean/.config/scripts/sbar.sh > /dev/null 2>&1 &
setwall $(cat /home/sean/.config/scripts/curwall)
exec dwm > ~/.local/share/dwm.log
